######################################################################
##
## Filename: midi_wave_reader_tb.udo
## Created on: Mon Dec 10 01:26:30 AM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
