######################################################################
##
## Filename: duration_timer_tb.udo
## Created on: Sun Oct 28 02:31:06 PM PDT 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
