######################################################################
##
## Filename: lab4_top_tb.udo
## Created on: Sun Oct 28 01:11:35 PM PDT 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
