######################################################################
##
## Filename: lab4_top.udo
## Created on: Sun Oct 28 02:01:24 PM PDT 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
