######################################################################
##
## Filename: mcu_tb.udo
## Created on: Fri Oct 26 07:31:45 PM PDT 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
