######################################################################
##
## Filename: music_player_tb.udo
## Created on: Sun Oct 28 10:40:13 AM PDT 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
