######################################################################
##
## Filename: music_player.udo
## Created on: Sun Oct 28 11:34:07 AM PDT 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
