######################################################################
##
## Filename: sine_reader_tb.udo
## Created on: Sun Oct 28 02:29:02 PM PDT 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
