######################################################################
##
## Filename: song_reader_tb.udo
## Created on: Fri Oct 26 07:38:58 PM PDT 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
