######################################################################
##
## Filename: dynamics_calc_tb.udo
## Created on: Sun Dec 09 11:11:34 PM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
