######################################################################
##
## Filename: midi_note_tb.udo
## Created on: Mon Dec 10 04:12:58 AM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
