######################################################################
##
## Filename: midi_msg_handler_tb.udo
## Created on: Mon Dec 10 12:41:39 AM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
