######################################################################
##
## Filename: sustain_variation_tb.udo
## Created on: Sun Dec 09 10:23:56 PM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
