######################################################################
##
## Filename: chords_tb.udo
## Created on: Tue Dec 04 07:51:21 PM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
