######################################################################
##
## Filename: chords.udo
## Created on: Wed Dec 05 10:43:33 PM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
