######################################################################
##
## Filename: music_player_tb.udo
## Created on: Thu Dec 06 01:40:34 AM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
