######################################################################
##
## Filename: note_player_tb.udo
## Created on: Sat Dec 08 08:58:44 PM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
