######################################################################
##
## Filename: piano_weight_tb.udo
## Created on: Tue Nov 27 09:30:19 PM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
