######################################################################
##
## Filename: piano_voice_tb.udo
## Created on: Thu Nov 29 12:11:26 PM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
