######################################################################
##
## Filename: sine_reader.udo
## Created on: Fri Dec 07 02:59:52 PM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
