######################################################################
##
## Filename: duration_timer2_tb.udo
## Created on: Thu Dec 06 12:42:39 AM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
