######################################################################
##
## Filename: midi_dynamics_tb.udo
## Created on: Sat Dec 01 05:01:26 PM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
