######################################################################
##
## Filename: song_reader_tb.udo
## Created on: Tue Dec 04 07:55:07 PM PST 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
