######################################################################
##
## Filename: blinker_tb.udo
## Created on: Sun Oct 21 09:53:46 PM PDT 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
