######################################################################
##
## Filename: lab3_top.udo
## Created on: Mon Oct 22 04:07:31 PM PDT 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
