######################################################################
##
## Filename: master_fsm_tb.udo
## Created on: Mon Oct 22 12:02:10 AM PDT 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
